version: '3.4'

services:
  daprfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "52001:50002"
      - "5001:80"

  daprbackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "52002:50002"

