version: '3.4'

services:
  daprfrontend:
    image: ${DOCKER_REGISTRY-}daprfrontend
    build:
      context: .
      dockerfile: DaprFrontEnd/Dockerfile

  daprfrontend-sidecar:
    image: "daprio/daprd:latest"
    command: ["./daprd","-app-id", "daprfrontend", "-app-port", "80", "-dapr-grpc-port", "50002"]
    depends_on:
      - daprfrontend
    network_mode: "service:daprfrontend"

  daprbackend:
    image: ${DOCKER_REGISTRY-}daprbackend
    build:
      context: .
      dockerfile: DaprBackend/Dockerfile

  daprbackend-sidecar:
    image: "daprio/daprd:latest"
    command: ["./daprd","-app-id", "daprbackend", "-app-port", "80", "-dapr-grpc-port", "50002"]
    depends_on:
      - daprbackend
    network_mode: "service:daprbackend"